# Generated by Django 4.2.20 on 2025-03-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='default_nickname', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
